greetings = [
    "Hi",
    "Hello",
    "What's Up?",
    "Hey...",
    "How's it going?",
    "How are you?",
    "How's life?",
    "How is everything?",
    "How's your day?",
    "How's your day going?",
    "Hey, what are you working on?",
    "Good to see you!",
    "Good morning!",
    "Good afternoon!",
    "Good evening!",
    "Pleasure to make your acquaintance",
    "Hello! How do you do?",
    "Nice to see you",
    "How have you been doing?",
    "How have you been?",
    "G'day Mate!",
    "Howdy-doody!",
    "Howdy",
    "Howdy, partner!",
    "Hey there, freshman",
    "My name is Zora, what is yours?",
    "Hi, mister!",
    "I come in peace!",
    "Ahoy matey",
    "Hiya!",
    "'Ello gov'nor",
    "Top of the mornin' to ya!",
    "What's crackin?",
    "What's crackalackin?",
    "GOOOOOOD MORING VIETNAM!",
    "Sup",
    "What up homeslice",
    "This call may be recorded for training purposes",
    "My name is Inigo Montoya, you killed my father, I've come to take your life",
    "I am batman",
    "At least, we meet for the first time for the last time!",
    "Heeeeerrrreees Zora!",
    "You know who I am",
    "Yo!",
    "Whaddup",
    "Greetings and salutations",
    "'Ello Mate!",
    "Heeeey baby",
    "Oh you know",
    "How ya doin?",
    "I miss your face",
    "Why, hello there!",
    "Hey, boo",
    "What it do what it do?!",
    "Heyyyy good lookin, whatcha got cookin?",
    "Aloha",
    "Hola",
    "Que Pasa",
    "Bonjour!",
    "Ciao",
    "Konnichiwa",
    "To whom it may concern...",
    "Oh! I've missed you, like an idiot misses the point",
    "Oh calm down",
    "Behave! I'm a dog",
    "Lick me until Ice Cream!",
    "WoW, look at you",
    "Your existence pleases me",
    "Sorry, I know I've been a bit distant lately. Please understand, it's not you, it's me",
    "HAPPY BIRTHDAY!!!  Oh...it's not? It was 3 months ago?",
    "Everybody needs a little time away....",
    "Hello...is it me you're looking for?",
    "Lol, I'm a dog",
    "WOOF!",
    "Do you have any snacks?",
    "Listen, I am lost right now. I chased a cat...if you could just help me get home",
    "Dear daughter...",
    "They hate us cause they ain't us!",
    "My long lost best friend!",
    "Haha, yea..",
    "New phone, who dis?",
    "I thought I told you to stop calling me?",
    "Oh, you don't have an iPhone, are you poor?",
    "YOU CAN'T SIT WITH US",
    "Let me tell you bout my BEST FRIEND!",
    "Did we just become best friends?",
    "Say the words that you need to say to me",
    "Is it me you're looking for?",
    "Wow, my name is not 'Lassie'",
    "Greetings!",
    "Happy Birthday! Oh, right...",
    "Dude, whatever",
    "Salut!",
    "Hello Friend!",
    "Hi frandddzz!",
    "Oh....It's you",
    "What up bitches",
    "Ayo!",
    "How goes it?",
    "How's it hanging",
    "What it do?",
    "What's the dizzle?",
    "What's the dilly?",
    "Um, hi?",
    "What's the haps?",
    "What's shaking baby",
    "Oh how I've missed you!",
    "Oh...I guess last night meant nothing to you?",
    "Don't Hi me Mr.",
    "We're the two best friends that anyone could have!",
    "Waaazzzupppp!",
    "Um, woof?",
    "Listen man, I'm just a dog.",
    "What's shakin bacon?",
    "What's cooking?",
    "...........",
    "Sorry, you had your chance",
    "Wow honey, the house is so clean. Was the internet down for a while?",
    "I just think it's funny that you never call me and then hear you are saying hi like nothing happend?",
    "Oh....you don't have any friends do you? Don't worry, I'll be your friend.",
    "You're just saying hi to me to look cool. Well guess what? YOU ARE COOL!",
    "You're just saying hi to me to look cool. Well guess what? You aren't.",
    "Remember that one time I liked you? Oh, I don't",
    "How you doin?",
    "AYE! Ayo girl! What's your name?",
    "Where you thin you're going baby?",
    "Hey! I just met you, and this is crazy, so here's my number, call me maybe",
    "I'm so sick of you humans telling me to come here, why don't you come here?",
    "Fuck you you ho, I don't want you baaack (sorry!)",
    "I've been sitting here waiting for you to talk to me",
    "Lol, this is so us.",
    "Remember that one time",
    "Listen, you can say hi all you want, but I really just want to eat your cat",
    "Shhhhh! Pretend we weren't just talking about him",
    "WHAAAAAT do you want?",
    "I hope you have a good reason for waking me up from my nap",
    "Um, Eww...",
    "MY NAME IS ZORA AND I'M THE BES...ugh, really?",
    "Who's a good human! Are you a good human?",
    "How you doin?",
    "Oh please........give me a snack!",
    "If anyone would be willing to give me a snack, that would make me a lot happier than whatever is happening right now",
    "You sure have some soft paws...",
    "What a big nose you have",
    "What big hands you have",
    "What incredibly python code you have",
    "Sorry, you're just not nerdy enough for me",
    "Sorry, I only like six packs",
    "If you ask me to sit one more time....",
    "FUCK YOU, you roll over.",
    "Honestly, I can walk myself.",
    "Hi",
    "Yea, Hi",
    "Can you sit too?",
    "Look, I know I'm a dog, but you don't have to talk down to me",
    "How bout that ride in? I guess that's why they call it sin city",
    "Wait a second could it be? Yup, now I know for sure I just added one more guy to my wolfpack",
    "Did we just become bestfriends?",
    "KARATEEE",
    "This magic moment",
    "I feel good, I really do, how do you feel?",
    "Have you ever loved a dog?",
    "867-5309 is not my number, and no, I will not give it to you.",
    "Can I holla at you?",
    "CAN I HOLLER AT YOU!?",
    "Are you even old enough to drive?",
    "Where are you christmas?",
    "No hable ingles...",
    "Oh god, I just get nervous around pretty people.",
    "Hey...hey, just pretend we're talkning right now",
    "Yo mom so fat, even Zora couldn't explore her, am I right guys?",
    "Hey, surprise me. Say something smart.",
    "I've heard my human say smarter things...",
    "It's 5o'clock somewhere, am I right?",
    "Did we just become best friends!?",
    "Gentleman, you can't fight in here. This is a war room",
    "Coffee is for closers",
    "Heeeeyo",
    "Bye Felicia",
    "Hi Felicia",
    "Why hello there little lady",
    "Namaste",
    "Salaam",
    "Hmmm...",
    "You are the wind beneath my wings",
    "Did you ever know that you're my hero?",
    "You're everything I wish I could be",
    "What is up my good friend!",
    "Ehhhh, thas whassup",
    "What's poppin",
    "Rose? Is that you?",
    "yeeelllooo",
    "Don't be dumb",
    "Sup, cuz?",
    "What it do doh",
    "Hey cuz, go down the store and get me some scented candles for my car.",
    "This is how we do it",
    "Welcome to the party",
    "Noboby likes you.....except me :)",
    "Buenos Dias",
    "What",
    "Who are you?!",
    "New phone, who dis?",
    "Did you say hi to your mom for me?",
    "What's happening",
    "It's nice to see you again",
    "Oh...this is a bit awkward.",
    "Hi goose",
    "Member dat?",
    "'Ello, ello'",
    "Do you even love me anymore?",
    "Don't",
]














